{% set name = "nengo-dl" %}
{% set version = "3.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nengo-dl-{{ version }}.tar.gz
  sha256: c0ca16c88196afc844a10d26d3e6a7c66b8e3a8f70d0dabbab4d08935735c975

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - jinja2
    - nengo >=3.0.0
    - numpy
    - packaging
    - progressbar2
    - python >={{ python_min }}
    - tensorflow >=2.2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - nengo_dl
    - nengo_dl.tests

about:
  home: https://www.nengo.ai/nengo-dl
  summary: Deep learning integration for Nengo
  license: LicenseRef-NENGO
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - Tobias-Fischer
